export const LANGUAGES = {
  'Afrikaans': 'afrikaans',
  'Albanian': 'albanian',
  'Amharic': 'amharic',
  'Arabic': 'arabic',
  'Armenian': 'armenian',
  'Assamese': 'assamese',
  'Azerbaijani': 'azerbaijani',
  'Bashkir': 'bashkir',
  'Basque': 'basque',
  'Belarusian': 'belarusian',
  'Bengali': 'bengali',
  'Bosnian': 'bosnian',
  'Breton': 'breton',
  'Bulgarian': 'bulgarian',
  'Catalan': 'catalan',
  'Chinese': 'chinese',
  'Croatian': 'croatian',
  'Czech': 'czech',
  'Danish': 'danish',
  'Dutch': 'dutch',
  'English': 'english',
  'Estonian': 'estonian',
  'Faroese': 'faroese',
  'Finnish': 'finnish',
  'French': 'french',
  'Galician': 'galician',
  'Georgian': 'georgian',
  'German': 'german',
  'Greek': 'greek',
  'Gujarati': 'gujarati',
  'Haitian creole': 'haitian creole',
  'Hausa': 'hausa',
  'Hawaiian': 'hawaiian',
  'Hebrew': 'hebrew',
  'Hindi': 'hindi',
  'Hungarian': 'hungarian',
  'Icelandic': 'icelandic',
  'Indonesian': 'indonesian',
  'Italian': 'italian',
  'Japanese': 'japanese',
  'Javanese': 'javanese',
  'Kannada': 'kannada',
  'Kazakh': 'kazakh',
  'Khmer': 'khmer',
  'Korean': 'korean',
  'Lao': 'lao',
  'Latin': 'latin',
  'Latvian': 'latvian',
  'Lingala': 'lingala',
  'Lithuanian': 'lithuanian',
  'Luxembourgish': 'luxembourgish',
  'Macedonian': 'macedonian',
  'Malagasy': 'malagasy',
  'Malay': 'malay',
  'Malayalam': 'malayalam',
  'Maltese': 'maltese',
  'Maori': 'maori',
  'Marathi': 'marathi',
  'Mongolian': 'mongolian',
  'Myanmar': 'myanmar',
  'Nepali': 'nepali',
  'Norwegian': 'norwegian',
  'Nynorsk': 'nynorsk',
  'Occitan': 'occitan',
  'Pashto': 'pashto',
  'Persian': 'persian',
  'Polish': 'polish',
  'Portuguese': 'portuguese',
  'Punjabi': 'punjabi',
  'Romanian': 'romanian',
  'Russian': 'russian',
  'Sanskrit': 'sanskrit',
  'Serbian': 'serbian',
  'Shona': 'shona',
  'Sindhi': 'sindhi',
  'Sinhala': 'sinhala',
  'Slovak': 'slovak',
  'Slovenian': 'slovenian',
  'Somali': 'somali',
  'Spanish': 'spanish',
  'Sundanese': 'sundanese',
  'Swahili': 'swahili',
  'Swedish': 'swedish',
  'Tagalog': 'tagalog',
  'Tajik': 'tajik',
  'Tamil': 'tamil',
  'Tatar': 'tatar',
  'Telugu': 'telugu',
  'Thai': 'thai',
  'Tibetan': 'tibetan',
  'Turkish': 'turkish',
  'Turkmen': 'turkmen',
  'Ukrainian': 'ukrainian',
  'Urdu': 'urdu',
  'Uzbek': 'uzbek',
  'Vietnamese': 'vietnamese',
  'Welsh': 'welsh',
  'Wolof': 'wolof',
  'Yiddish': 'yiddish',
  'Yoruba': 'yoruba',
} as const

export const LANGUAGE_BEHAVIOURS = {
  'Manual': 'manual',
  'Automatic single language': 'automatic single language',
  'Automatic multiple languages': 'automatic multiple languages',
} as const

export const OUTPUT_FORMATS = {
  Json: 'json',
  Srt: 'srt',
  Vtt: 'vtt',
  Txt: 'txt',
  Plain: 'plain',
} as const
